StockManagementWebApp/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StockManagementWebApp.Models;

namespace StockManagementWebApp.Controllers
{
    public class CompaniesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Companies
        public ActionResult Index()
        {
            var companies = db.Companies.Include(c => c.Category);
            return View(companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           Company company = db.Companies.Include(c=>c.Category).SingleOrDefault(c=>c.Id==id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RegistrationCode,Name,CategoryId")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", company.CategoryId);
            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", company.CategoryId);
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegistrationCode,Name,CategoryId")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", company.CategoryId);
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Include(c => c.Category).SingleOrDefault(c => c.Id == id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockManagementWebApp/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;
using StockManagementWebApp.Models;

namespace StockManagementWebApp.Controllers
{
    public class StockController : Controller
    {
        private ApplicationDbContext db;

        public StockController()
        {
            db = new ApplicationDbContext();

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Index()
        {
           
            return View(db.StockIns.Include(s=>s.Company).Include(s=>s.Item).ToList());
        }

        [HttpGet]
        public ActionResult Stockin()
        {
            ViewBag.Company = db.Companies.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Stockin(StockIn stockIn)
        {
            ViewBag.Company = db.Companies.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();
            var exist = db.StockIns.Count(s => s.ItemId == stockIn.ItemId);
            if (exist > 0)
            {
                var stock = db.StockIns.SingleOrDefault(s => s.ItemId == stockIn.ItemId);
                stock.CompanyId = stockIn.CompanyId;
                stock.ItemId = stockIn.ItemId;
                stock.TotalQuantity =stock.TotalQuantity+ stockIn.TotalQuantity;


            }
            else
            {
                db.StockIns.Add(stockIn);
                
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public JsonResult GetItemByCompanyId(int companyId)
        {
            var items = db.Items.Where(i => i.CompanyId == companyId).Select(i => new SelectListItem { Value = i.Id.ToString(), Text = i.ItemName }).ToList();
            return Json(items);
        }

        public JsonResult GetdataByItemId(int iId)
        {
            var exist = db.StockIns.Count(s => s.ItemId==iId);
            if (exist>0)
            {
                var stockin = db.StockIns.Include(s => s.Item).SingleOrDefault(s => s.ItemId == iId);
                return Json(stockin);
            }
            var stockIn = new StockIn();
            stockIn.TotalQuantity = 0;
            stockIn.Item = db.Items.SingleOrDefault(i=>i.Id==iId);



            return Json(stockIn);
        }

        [HttpGet]
        public ActionResult StockOut()
        {
            ViewBag.Company = db.Companies.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult StockOut(List<StockOut> stockOuts )
        {
            ViewBag.Company = db.Companies.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name }).ToList();

            foreach (var stockOut in stockOuts)
            {
                var stockIndb = db.StockIns.SingleOrDefault(s => s.ItemId == stockOut.ItemId);
                if (stockIndb != null) stockIndb.TotalQuantity = stockIndb.TotalQuantity - stockOut.TotalQuantity;


                db.StockOuts.Add(stockOut);
                
            }
           var result= db.SaveChanges();

            if (result>0)
            {
                var msg = "Record Save SuccessFull";
                return Json(msg);
            }
            else
            {
                var msg = "Record Save SuccessFull";
                return Json(msg);
            }
            



        }








    }
}

StockManagementWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
	<head>	
		<meta charset="utf-8" />			
		<meta name="viewport" content="width=device-width, initial-scale=1.0">		
		<title>@ViewBag.Title -Stock ManageMent System|Application</title>
		@Styles.Render("~/Content/css")
		@Scripts.Render("~/bundles/modernizr")
	
		
		<link rel="stylesheet" href="style.css"/>
	</head>
	
<body>
	<header id="header">	
				<div class="full_body ">
					<div  class="container">
			
						<nav>
							<ul id="menu">
								<li>@Html.ActionLink("Home","Index","Home")</li>
								<li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                                <li>@Html.ActionLink("Company", "Index", "Companies")</li>
                                <li>@Html.ActionLink("Items", "Index", "Items")</li>
								<li><a href="#">Stock</a>
									<ul>
										<li>@Html.ActionLink("Stock In","Stockin","Stock")</li>
										<li>@Html.ActionLink("Stock Out","StockOut","Stock")</li>
										
									</ul>			
								</li>
								<li><a href="#">Javascript</a></li>
								@Html.Partial("_LoginPartial")
							</ul>
							
						</nav>	
			
				</div>
			</div>	
	</header>

<div class="full_body">
	<div class="container maincontent">
	        @RenderBody()
	</div>
</div>

<div class="full_body ">
		<div class="container">
			<footer>
			
			<div id="usefull_link">
			<h2>Usefull link</h2>
				<a href="https://facebook.com/sourav4439">&#10148;Developer Profile</a><br />
			    
				
			</div>
			
			
			<div id="social_area">
				<h2>Stock management systems </h2>
				
				
					<ul>
						<li class="facebook"><a href="#" target="_blank"></a></li>
						<li class="twitter"><a href="#"></a></li>
						<li class="google"><a href="#"></a></li>
						<li class="youtube"><a href="#"></a></li>
					</ul>
					<p> &copy; @DateTime.Now.Year-All Rights Reserved by Sourav Singha</p>
				</div>
			
			<div id="any_query">
				<h2>Any Query</h2>
					
					<p>Mob:+880139214439</p>
					<p></p>
				
			</div>
			</footer>
		
		
		
		</div>
		
		
		
</div>	

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>	
	
</html>
<!--
<div class="full_body">
	<div class="fix container">
	


	</div>
</div>


-->
	